version: '3'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - ${HOST_PORT}:${DOCKER_DB_PORT}
    environment:
      - POSTGRES_USER=${DOCKER_DB_USER}
      - POSTGRES_PASSWORD=${DOCKER_DB_PASS}
      - POSTGRES_DB=${DOCKER_DB_NAME}
    networks:
      - pg_net
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DOCKER_PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DOCKER_PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - pg_net

networks:
  pg_net: